const DEFAULT_PREDELAY = 30;

export default
    {
        TIME: {
            START_DELAY: 500,
            SCORE_SPEED: 100,
            SHARP_PREDELAY: 0,
            SHARP_POSTDELAY: 0,
        },
        // ["C1#", (beat), preDelay%, postDelay%],
        MAIN_HORN: [
            [0, 0.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["D2", 0.5, DEFAULT_PREDELAY,],
            ["C2", 1, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 1, DEFAULT_PREDELAY,],
            ["D1", 0.5, DEFAULT_PREDELAY,],
            ["G1", 2, DEFAULT_PREDELAY,],
            [0, 1, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["G1", 0.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["D2", 1, DEFAULT_PREDELAY,],
            ["E2", 0.5, DEFAULT_PREDELAY,],
            ["F2", 0.5, DEFAULT_PREDELAY,],
            ["C2", 2.5, DEFAULT_PREDELAY,],
            [0, 2.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["D2", 0.5, DEFAULT_PREDELAY,],
            ["C2", 1, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 1, DEFAULT_PREDELAY,],
            ["D1", 0.5, DEFAULT_PREDELAY,],
            ["G1", 2, DEFAULT_PREDELAY,],
            [0, 1, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["G1", 0.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["D2", 0.5, DEFAULT_PREDELAY,],
            [0, 0.5, DEFAULT_PREDELAY,],
            ["E2", 0.5, DEFAULT_PREDELAY,],
            ["F2", 0.5, DEFAULT_PREDELAY,],
            ["C2", 2.5, DEFAULT_PREDELAY,],
            [0, 2, DEFAULT_PREDELAY,],

            [0, 1, DEFAULT_PREDELAY,],
            ["A1", 1, DEFAULT_PREDELAY,],
            ["F1", 1, DEFAULT_PREDELAY,],
            ["D2", 1, DEFAULT_PREDELAY,],
            ["C2", 1.5, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 2, DEFAULT_PREDELAY,],

            [0, 2.5, DEFAULT_PREDELAY,],
            ["F2", 0.5, DEFAULT_PREDELAY,],
            ["E2", 0.5, DEFAULT_PREDELAY,],
            ["D2", 0.5, DEFAULT_PREDELAY,],
            ["C2", 1.5, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 2, DEFAULT_PREDELAY,],
            
            [0, 2.5, DEFAULT_PREDELAY,],
            ["F2", 0.5, DEFAULT_PREDELAY,],
            ["E2", 0.5, DEFAULT_PREDELAY,],
            ["D2", 0.5, DEFAULT_PREDELAY,],
            ["E2", 1.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["A1", 2, DEFAULT_PREDELAY,],
            
            [0, 2, DEFAULT_PREDELAY,],
            ["G1#", 0.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["B1", 0.5, DEFAULT_PREDELAY,],
            ["C2#", 1, DEFAULT_PREDELAY,],
            ["E2", 0.5, DEFAULT_PREDELAY,],
            ["A2", 2, DEFAULT_PREDELAY,],

            [0, 3.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["D2", 0.5, DEFAULT_PREDELAY,],
            ["C2", 0.5, DEFAULT_PREDELAY,],
            ["A1", 0.5, DEFAULT_PREDELAY,],
            ["F1", 0.5, DEFAULT_PREDELAY,],
            ["D1", 2.5, DEFAULT_PREDELAY,],
            ["F1", 0.125, DEFAULT_PREDELAY,],
            ["F1#", 0.125, DEFAULT_PREDELAY,],
            ["G1", 2, DEFAULT_PREDELAY,],
        ],
    }